name: Test pip installation

on:
  release:
    types: [published, created]

jobs: 
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install napiod via pip
        run: |
          pip install napiod
      - name: Test installation
        run: |
          python -c "import napiod;"
      - name: Checkout tests
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            tests
      - name: extract tests
        run: |
          echo "PWD:"
          echo $PWD
          echo "-----------------------------"
          echo "ls"
          ls
          echo "-----------------------------"
      - name: Test with pytest
        run: |
          echo $PWD
          pip install pytest
          pytest tests/*_test.py

